development:
  adapter: postgresql
  encoding: unicode
  database: agh_tdd_development
  pool: 5
  username: agh_tdd
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: agh_tdd_test
  pool: 5
  username: agh_tdd
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: agh_tdd_production
  pool: 5
  username: agh_tdd
  password:
